//! Residual vs plain on the REAL EmbeddingGemma dataset (n=2000 + 100
//! queries, dim=768, generated by cto/scripts/gen_embeddings.py into
//! /tmp/vecq-bench). Ignored by default: the dataset is not reproducible
//! in CI. Run locally in release before merging estimator/format changes:
//!   cargo test -p vecq-core --release --test real_residual_validation -- --ignored --nocapture

use vecq_core::VecqIndex;

fn read_f32s(path: &str) -> Vec<f32> {
    let bytes = std::fs::read(path).expect(path);
    bytes
        .chunks_exact(4)
        .map(|b| f32::from_le_bytes([b[0], b[1], b[2], b[3]]))
        .collect()
}

fn cosine(a: &[f32], b: &[f32]) -> f32 {
    let dot: f32 = a.iter().zip(b).map(|(x, y)| x * y).sum();
    dot / 1.0 // both already unit-norm (EmbeddingGemma output normalized)
}

#[test]
#[ignore = "requires the real EmbeddingGemma dataset in /tmp/vecq-bench (gen_embeddings.py)"]
fn real_dataset_residual_vs_plain() {
    let (n, nq, dim) = (2000usize, 100usize, 768usize);
    let base = read_f32s("/tmp/vecq-bench/base.f32");
    let queries = read_f32s("/tmp/vecq-bench/queries.f32");
    assert_eq!(base.len(), n * dim);
    assert_eq!(queries.len(), nq * dim);
    let base_v: Vec<&[f32]> = base.chunks(dim).collect();
    let queries_v: Vec<&[f32]> = queries.chunks(dim).collect();

    let exact_top = |q: &[f32], k: usize| -> Vec<usize> {
        let mut s: Vec<(usize, f32)> = base_v
            .iter()
            .enumerate()
            .map(|(i, v)| (i, cosine(q, v)))
            .collect();
        s.sort_by(|a, b| b.1.partial_cmp(&a.1).unwrap());
        s.into_iter().take(k).map(|(i, _)| i).collect()
    };

    let mut plain = VecqIndex::new(dim, 42);
    let mut resid = VecqIndex::with_residual(dim, 42);
    let t0 = std::time::Instant::now();
    for v in &base_v {
        plain.add(v);
        resid.add(v);
    }
    let build = t0.elapsed();

    for (label, idx) in [("plain", &plain), ("resid", &resid)] {
        let t1 = std::time::Instant::now();
        let (mut r1, mut r10) = (0f32, 0f32);
        let mut max_score = 0f32;
        for q in &queries_v {
            let truth = exact_top(q, 10);
            let got = idx.search(q, 10);
            for (_, s) in &got {
                if *s > max_score {
                    max_score = *s;
                }
            }
            r1 += if got[0].0 == truth[0] { 1.0 } else { 0.0 };
            r10 += truth
                .iter()
                .filter(|t| got.iter().any(|(i, _)| i == *t))
                .count() as f32
                / 10.0;
        }
        let dt = t1.elapsed();
        println!(
            "{label}: recall@1 {:.3} recall@10 {:.3} | {:.3} ms/q | max score {:.6} (<=1 sanity) | build +search {:?}",
            r1 / nq as f32,
            r10 / nq as f32,
            dt.as_secs_f64() * 1000.0 / nq as f64,
            max_score,
            build
        );
    }
}
